### ISSUE TITLE
Issues with testing Zarr reader branch

### ISSUE THREAD

**Issue by Christianfoley** [mehta-lab/microDL#174]
In testing Jenny's zarr reading PR I've come across multiple bugs, I believe more thorough testing is also needed to make sure that the issue's weren't with my testing scripts. Here they are in order of urgency:

1. The reader determines whether to use zarr or tiff image reading by the presence of a `frames_meta.csv` metadata file in the image directory. However, after preprocessing it generates this file and leaves it in the directory. The next time the zarr folder is preprocessed (perhaps with different parameters) the preprocessing breaks, because it sees the existing metadata of the last preprocessing cycle and tries to read tiff files (when the data is in fact zarr format). There should be some other way to determine whether we are reading from zarr or not.

2. It seems that I am unable to run preprocessing (of any two directories of either file format) twice consecutively in the same script. Some very strange behavior happens where assertion errors about the config's `flat_field` and 'mask_dir' parameters fails when they definitely should not (they detect some parameter that doesn't exist, etc). This should be looked into more.

3. I cannot seem to generate masks from certain channels in .zarr files. I've traced the problem down to a `ValueError: cannot convert float NaN to integer` when attempting to read the `channel_idx` from the auto-generated `frames_meta.csv` metadata. Perhaps the typing of that parameter is incorrect when autogenerated

4. If a user generates the `frames_meta.csv'` metadata while mounted differently (for example if they are accessing a data folder through `/gpfs/projects/CompMicro..` or `/home/their.user/CompMicro/..`), then running preprocessing on that data from any other mounting will fail, as the metadata captures that mounting's absolute path as the path to the reconstructed images in each folder. I had to write a script to go in and convert these paths to `/hpc/projects/CompMicro/..` before using the data to test preprocessing.

There were a few other issues I ran into, but I believe they might have been symptoms of these main ones. Hopefully fixing these will allow for smooth usage of the `.zarr` reading.

The scripts I have used for this testing can be found in `/hpc/projects/comp_micro/projects/virtualstaining/testing_zarr_scripts`.

**Comment by jennyfolkesson** [comment]
Thank you @Christianfoley for testing this branch. I took your main testing script and checked it in with the rest of the code here:
https://github.com/mehta-lab/microDL/blob/zarr_reader/tests/test_zarr_reading.py

I had to modify it because, as discussed, channel indices don't match between zarr and tiff processing. If you feel like something is missing in the test script, please let me know or add it yourself, whatever you prefer.

Not in the current version of the test but I did try running zarr reading twice consecutively and it didn't generate any errors after updating the code.

What I have not addressed is removing the absolute paths. I do think that would be very useful and should be implemented, but I'd prefer to save it for a separate PR if that's ok.

**Comment by Christianfoley** [comment]
Hi Jenny, sorry I missed this on Friday. I took a look at the modifications you made to the testing script, it looks good to me! (Thanks for making it more robust). 

As for the absolute paths issue. I think this issue should be addressed alongside the saving permissions one. Perhaps we should push that off to 2.0 or 2.1, and have a single PR where we sweep through the code and change automatic writing permissions and absolute path creation.
